import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Dashboard</Link>
        </li>
        <li>
          <Link to="/dashboardwithgeneralwaste">Dashboardwithgeneralwaste</Link>
        </li>
        <li>
          <Link to="/dashboardwithwaterusage">Dashboardwithwaterusage</Link>
        </li>
        <li>
          <Link to="/settingslogout">SettingsLogout</Link>
        </li>
        <li>
          <Link to="/generalwaste">GeneralWaste</Link>
        </li>
        <li>
          <Link to="/transportation1">Transportation1</Link>
        </li>
        <li>
          <Link to="/waterusage">WaterUsage</Link>
        </li>
        <li>
          <Link to="/transportation2">Transportation2</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
